version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
    commands:
      - mvn clean install
  build:
    commands:
      - mvn package
      - echo 'getting files from s3'
      - aws s3 cp s3://kbaafi-buildspec-demo/myzippy.zip .
      - echo 'unzipping myzippy.zip.....'
      - unzip myzippy.zip
      - echo 'listing files.....'
      - ls

  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker build -t $APP_REPO:latest .
      - docker push $APP_REPO:latest